/* 首页piece模块 */
export const STORE_NOTE_RESOURCE = 'STORE_NOTE_RESOURCE'

export const SWITCH_PIECE_DATA = 'SWITCH_PIECE_DATA'

export const SWITCH_PIECE_PERFORM = 'SWITCH_PIECE_PERFORM'

export const SWITCH_PIECE_ONOFF = 'SWITCH_PIECE_ONOFF'

export const INIT_PIECE_LIST = 'INIT_PIECE_LIST'

export const SHOW_NOTIFY_MSG = 'SHOW_NOTIFY_MSG'